apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  dbUserName: dXNlcg==   #echo -n "user" | base64
  dbPassword: cGFzc3dvcmQ=   #echo -n "password" | base64
  dbName:     bXlkYXRhYmFzZQ==    #echo -n "mydatabase" | base64